from typing import List, Literal
from pydantic import BaseModel, Field
from models import azure_chatopenai_model, google_model
import json
from langchain.agents import create_agent

from logger.base_logger import get_logger
logger = get_logger(__name__)


class ContentItem(BaseModel):
    type: Literal["markdown", "csv", "plotly_plot_json","text", "document"]
    content: str | None = Field(default=None)
    filename: str | None = Field(default=None)


class ResponseModel(BaseModel):
    content: List[ContentItem]


def format_response(user_query: str, answer: str) -> str:
    """
    Formats agent response into structured JSON list
    """
    try:
        logger.info(
            f"Inside format_response | user_query: {user_query} | answer: {answer}"
        )

        template = f"""
        You are a smart response-generation agent designed to produce structured, clear, and user-friendly outputs from multi-source inputs.

        From the user's query and the response generated by the agent, create a clear structured response.
        - Identify the user’s intent and the specific information requested.
        - Rephrase content to be clear, concise, and easy to understand.  
        - Avoid repetition, or vague language.
         Emoji usage
        - In the final output, enhance readability with relevant professional markdown-style emojis (e.g., `:information_source:`, `:bar_chart:`, `:warning:`). Avoid overuse.
        - Do not give out any file paths/file names in the markdown response, do not include the user query in the response, only include the answer to the user query in the markdown response. 
        - Any file ending with .pdf should be categorized as a document, .csv as csv, .json as plotly_plot_json, .txt as text.
        Return ONLY a JSON list.

        Allowed formats:

        1. {{ "type": "markdown", "content": "<markdown text>" }}
        2. {{ "type": "csv", "filename": "<filename>.csv" }}
        3. {{ "type": "text", "filename": "<filename>.txt" }}
        4. {{ "type": "plotly_plot_json", "filename": "<filename>.json" }}
        5. {{ "type": "document", "filename": "<filename>.pdf" }}

        Rules:
        - Only these 5 types allowed
        - No explanations outside JSON
        - Output must be valid JSON list
        - Always include a markdown which includes the response to the user query. Do not include any file paths in the response, only the filenames to be included. Response should be user-friendly and easily understandable answering the user's query.

        User Query:
        {user_query}

        Agent Response:
        {answer}
        """

        agent = create_agent(
            model=google_model,#azure_chatopenai_model,
            response_format=ResponseModel
        )
       
        result = agent.invoke({
            "messages": [{"role": "user", "content": template}]
        })
        structured_output = result["structured_response"]
        
        formatted_list = [
        {
            "type": item.type,
            "content": item.content,
            "filename": item.filename
        }
        for item in structured_output.content
        ]
        sans= json.dumps(formatted_list, ensure_ascii=False)

        safe_answer = sans.encode("utf-8", "ignore").decode()
        print(f"Formatted response: {safe_answer}")

        return json.dumps(formatted_list)


    except Exception as e:
        logger.error(f"Error in response writer invoke method: {e}")

        fallback = [
            {
                "type": "markdown",
                "content": "Unable to process your query, please try again later."
            }
        ]
        return json.dumps(fallback)
